<?php
$jieqiBlocks['0'] = array (
  'bid' => 0,
  'blockname' => '作者作品',
  'module' => 'article',
  'filename' => 'block_aarticles',
  'classname' => 'BlockArticleAarticles',
  'side' => -1,
  'title' => '',
  'vars' => 'lastupdate,4,0,$author',
  'template' => 'ruoxia_auqita.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['1'] = array (
  'bid' => 0,
  'blockname' => '粉丝排行榜',
  'module' => 'article',
  'filename' => 'block_credit',
  'classname' => 'BlockArticleCredit',
  'side' => -1,
  'title' => '',
  'vars' => 'point,10,0,id',
  'template' => 'block_credit.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['2'] = array (
  'bid' => 0,
  'blockname' => '我的粉丝值',
  'module' => 'article',
  'filename' => 'block_mycredit',
  'classname' => 'BlockArticleMycredit',
  'side' => -1,
  'title' => '我的粉丝值',
  'vars' => 'id',
  'template' => 'block_mycredit.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['3'] = array (
  'bid' => 0,
  'blockname' => '作者推荐',
  'module' => 'article',
  'filename' => 'block_commend',
  'classname' => 'BlockArticleCommend',
  'side' => '-1',
  'title' => '作者推荐',
  'vars' => '361|362|363|364',
  'template' => 'wap_index_list1.html',
  'contenttype' => 1,
  'custom' => 0,
  'publish' => '3',
  'hasvars' => 2,
  'showtype' => 0,
);
$jieqiBlocks['4'] = array (
  'bid' => 0,
  'blockname' => '精彩推荐',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '',
  'vars' => 'allvote,4,0,0,0,0',
  'template' => 'wap_index_list1.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

?>