<?php
$jieqiBlocks['0'] = array (
  'bid' => '1',
  'blockname' => '本站公告',
  'module' => 'system',
  'filename' => '',
  'classname' => 'BlockSystemCustom',
  'side' => '4',
  'title' => '本站公告',
  'vars' => '',
  'template' => '',
  'contenttype' => '1',
  'custom' => '1',
  'publish' => '3',
  'hasvars' => '0',
);
$jieqiBlocks['1'] = array (
  'bid' => '2',
  'blockname' => '用户登录',
  'module' => 'system',
  'filename' => 'block_login',
  'classname' => 'BlockSystemLogin',
  'side' => '0',
  'title' => '用户登录',
  'vars' => '',
  'template' => '',
  'contenttype' => '4',
  'custom' => '0',
  'publish' => '3',
  'hasvars' => '0',
);
$jieqiBlocks['2'] = array (
  'bid' => '21',
  'blockname' => '小说搜索',
  'module' => 'article',
  'filename' => 'block_search',
  'classname' => 'BlockArticleSearch',
  'side' => '1',
  'title' => '小说搜索',
  'vars' => '',
  'template' => '',
  'contenttype' => '0',
  'custom' => '0',
  'publish' => '3',
  'hasvars' => '0',
);
$jieqiBlocks['3'] = array (
  'bid' => '103',
  'blockname' => '新闻类别列表',
  'module' => 'news',
  'filename' => 'block_newsclass',
  'classname' => 'BlockNewsClass',
  'side' => '0',
  'title' => '新闻类别',
  'vars' => '16,5',
  'template' => 'block_newsclass.html',
  'contenttype' => '1',
  'custom' => '0',
  'publish' => '3',
  'hasvars' => '1',
);
$jieqiBlocks['4'] = array (
  'bid' => '63',
  'blockname' => '友情链接',
  'module' => 'link',
  'filename' => 'block_linklist',
  'classname' => 'BlockLinkLinklist',
  'side' => '8',
  'title' => '友情链接',
  'vars' => '10,2,0,64',
  'template' => 'block_linklist.html',
  'contenttype' => '1',
  'custom' => '0',
  'publish' => '3',
  'hasvars' => '1',
);
$jieqiBlocks['5'] = array (
  'bid' => '49',
  'blockname' => '用户书架',
  'module' => 'article',
  'filename' => 'block_ubookcase',
  'classname' => 'BlockArticleUbookcase',
  'side' => '6',
  'title' => '我的书架',
  'vars' => 'lastupdate,10,0,uid',
  'template' => 'block_shujia.html',
  'contenttype' => '4',
  'custom' => '0',
  'publish' => '2',
  'hasvars' => '1',
);

?>