<?php
/**
 * Created by PhpStorm.
 * User: burn
 * Date: 2017/2/13
 * Time: 下午8:16
 *
 * 小说分类列表
 *
 */

namespace Admin\Controller;
use Think\Db\Driver\Mysql;
use Think\Model;

class SortController extends BaseController
{
	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		
		$this->dirPath = C('DIR_PATH');
	}
	
	/**
	 * 获取频道分类
	 */
	public function firstSortList()
	{
		$filePath = C('FIRST_SORT_FILE_PATH');
		
		include_once $this->dirPath . $filePath;
		
		if(isset($jieqiFilter['article']['rgroup']) && $jieqiFilter['article']['rgroup'])
		{
			foreach($jieqiFilter['article']['rgroup'] as $key => $value)
			{
				$channel['id']   = $value['rgroup'];//频道id
				
				$channel['name'] = iconv('GBK','utf-8',$value['caption']);//频道id
			
				$channelList[]   = $channel;
			
			}
		}
		
		$this->assign('channelList',$channelList);
		
		$this->display();
	}
	
	public function secondSortList()
	{
		$filePath = C('SECONDE_SORT_FILE_PATH');
		
		include_once $this->dirPath . $filePath;
		
		if(isset($jieqiSort['article']) && $jieqiSort['article'])
		{
			foreach($jieqiSort['article'] as $key => $value)
			{
				$sort['channel'] = $value['group'] == 1 ? '男频' : '女频';//频道
				
				$sort['id']      = $key;//分类名称
				
				$sort['name']    = iconv('GBK','utf-8',$value['caption']);//分类名称
				
				$sortList[]      = $sort;
				
			}
		}
		
		$this->assign('sortList',$sortList);
		
		$this->display();
	}
	
	public function thirdSortList()
	{
		$filePath = C('THIRD_SORT_FILE_PATH');
		
		include_once $this->dirPath . $filePath;
		
		if(isset($jieqiSort['article']) && $jieqiSort['article'])
		{
			foreach($jieqiSort['article'] as $key => $value)
			{
				$sort['channel'] = $value['group'] == 1 ? '男频' : '女频';//频道
				
				$sort['sortid']  = $key;//小说分类id
				
				$sort['sort']    = iconv('GBK','utf-8',$value['caption']);//分类名称
				
				if(isset($jieqiSort['article'][$key]['types']) && $jieqiSort['article'][$key]['types'])
				{
					foreach($jieqiSort['article'][$key]['types'] as $typeKey => $typeValue)
					{
						$sort['id']   = $typeKey;
						
						$sort['name'] = iconv('GBK','utf-8',$typeValue);//分类名称;
						
						$sortList[] = $sort;
					}
				}
			}
		}
		
		$this->assign('sortList',$sortList);
		
		$this->display();
	}
}